#!/bin/bash

TEMPLATE_AUTHOR_FORMAT="%an <%ae>"
TEMPLATE_AUTHOR_NAME_FORMAT="%an"
TEMPLATE_AUTHOR_EMAIL_FORMAT="%ae"

TEMPLATE_COMMITTER_FORMAT="%cn <%ce>"
TEMPLATE_COMMITTER_NAME_FORMAT="%cn"
TEMPLATE_COMMITTER_EMAIL_FORMAT="%ce"

TEMPLATE_COMMIT_MESSAGE_SUBJECT_FORMAT="%s"
TEMPLATE_COMMIT_MESSAGE_SUBJECT_SANITIZED_FORMAT="%f"
TEMPLATE_COMMIT_MESSAGE_BODY_FORMAT="%b"

git_log_format() {
  pattern="$1"
  reference="$2"
  git log -1 --pretty=format:"$pattern" "$reference"
}

echo "+ GIT_COMMIT_* environment variables"
{
  echo "GIT_COMMIT_AUTHOR=$(git_log_format "${TEMPLATE_AUTHOR_FORMAT}" "HEAD")"
  echo "GIT_COMMIT_AUTHOR_NAME=$(git_log_format "${TEMPLATE_AUTHOR_NAME_FORMAT}" "HEAD")"
  echo "GIT_COMMIT_AUTHOR_EMAIL=$(git_log_format "${TEMPLATE_AUTHOR_EMAIL_FORMAT}" "HEAD")"

  echo "GIT_COMMIT_COMMITTER=$(git_log_format "${TEMPLATE_COMMITTER_FORMAT}" "HEAD")"
  echo "GIT_COMMIT_COMMITTER_NAME=$(git_log_format "${TEMPLATE_COMMITTER_NAME_FORMAT}" "HEAD")"
  echo "GIT_COMMIT_COMMITTER_EMAIL=$(git_log_format "${TEMPLATE_COMMITTER_EMAIL_FORMAT}" "HEAD")"

  echo "GIT_COMMIT_MESSAGE_SUBJECT=$(git_log_format "${TEMPLATE_COMMIT_MESSAGE_SUBJECT_FORMAT}" "HEAD")"
  echo "GIT_COMMIT_MESSAGE_SUBJECT_SANITIZED=$(git_log_format "${TEMPLATE_COMMIT_MESSAGE_SUBJECT_SANITIZED_FORMAT}" "HEAD")"
  echo 'GIT_COMMIT_MESSAGE_BODY<<GIT_COMMIT_MESSAGE_BODY_EOF'
  echo "$(git_log_format "${TEMPLATE_COMMIT_MESSAGE_BODY_FORMAT}" "HEAD")"
  echo 'GIT_COMMIT_MESSAGE_BODY_EOF'
} | tee "$GITHUB_ENV"
